### PR TITLE
Initial support for WCA States.

### PR DESCRIPTION
**Pull request by viroulep**
Implementation for thewca/wca-regulations#406.

Extending the compiler to handle the WCA States list was not that hard, but it makes some part a bit awkward, since the generate part used to expect 2 ASTs (one for the Regulations, one for the Guidelines).

I created a separate entry points for this particular input: `wrc-states`. Options are pretty much the same, I just changed the targets available.

An input file such as:
```markdown
# <wca-title>WCA List of Recognized States
<wca-states>
<version>Version: April 18, 2016

## Notes

Asia: AS
Europe: EU
North America: NA
South America: SA
Africa: AF
Oceania: OC

The WCA recognizes a total of 199 independent states. 

## <states-list>UN Member States:

- (AF:AS) Afghanistan
- (AL:EU) Albania
- (DZ:AF) Algeria
- (AD:EU) Andorra
- (AO:AF) Angola
- (AG:NA) Antigua and Barbuda
- (AR:SA) Argentina
- (AM:EU) Armenia
- (AU:OC) Australia
- (AT:EU) Austria
- (AZ:AS) Azerbaijan
- (BS:NA) Bahamas
- (BH:AS) Bahrain
- (BD:AS) Bangladesh
- (BB:NA) Barbados
- (BY:EU) Belarus
- (BE:EU) Belgium
- (BZ:NA) Belize
- (BJ:AF) Benin
```

Gives this html:
```erb
<% provide(:title, 'WCA List of Recognized States') %>
<div class="container"><h1>WCA List of Recognized States</h1>
<div class="version">Version: April 18, 2016<br/>[<code><a href="https://github.com/thewca/wca-regulations/tree/official/">official</a>:<a href="https://github.com/thewca/wca-regulations/commits/unknown">unknown</a></code>]</div>
<h2 id="notes">Notes</h2>
<p>Asia: AS<br />
Europe: EU<br />
North America: NA<br />
South America: SA<br />
Africa: AF<br />
Oceania: OC</p><p>The WCA recognizes a total of 199 independent states. <br />
</p>
<h2 id="un-member-states:">UN Member States:</h2>

<ul>
<li>Afghanistan</li>
<li>Albania</li>
<li>Algeria</li>
<li>Andorra</li>
<li>Angola</li>
<li>Antigua and Barbuda</li>
<li>Argentina</li>
<li>Armenia</li>
<li>Australia</li>
<li>Austria</li>
<li>Azerbaijan</li>
<li>Bahamas</li>
<li>Bahrain</li>
<li>Bangladesh</li>
<li>Barbados</li>
<li>Belarus</li>
<li>Belgium</li>
<li>Belize</li>
<li>Benin</li>
</ul>
</div>
```

and this seeds file:

```rb
# frozen_string_literal: true

sql = "INSERT INTO `Countries` (`id`, `name`, `continentId`, `iso2`) VALUES
('Afghanistan', 'Afghanistan', '_Asia', 'AF'),
('Albania', 'Albania', '_Europe', 'AL'),
('Algeria', 'Algeria', '_Africa', 'DZ'),
('Andorra', 'Andorra', '_Europe', 'AD'),
('Angola', 'Angola', '_Africa', 'AO'),
('Antigua and Barbuda', 'Antigua and Barbuda', '_North America', 'AG'),
('Argentina', 'Argentina', '_South America', 'AR'),
('Armenia', 'Armenia', '_Europe', 'AM'),
('Australia', 'Australia', '_Oceania', 'AU'),
('Austria', 'Austria', '_Europe', 'AT'),
('Azerbaijan', 'Azerbaijan', '_Asia', 'AZ'),
('Bahamas', 'Bahamas', '_North America', 'BS'),
('Bahrain', 'Bahrain', '_Asia', 'BH'),
('Bangladesh', 'Bangladesh', '_Asia', 'BD'),
('Barbados', 'Barbados', '_North America', 'BB'),
('Belarus', 'Belarus', '_Europe', 'BY'),
('Belgium', 'Belgium', '_Europe', 'BE'),
('Belize', 'Belize', '_North America', 'BZ'),
('Benin', 'Benin', '_Africa', 'BJ');"
ActiveRecord::Base.connection.execute(sql)
```

### CODE REVIEW

**Comment by jfly** [comment]
Just glanced through the diff. Could you write up how you envision this tool being used? Will the WRC send in a PR that updates the countries seeds file in the worldcubeassociation.org repository? What about a migration so our production database gets updated?

I'd be okay with the wca deploy script doing a diff between what's currently in mysql and what the wca regulations compiler tells us *should* be in mysql, and updating the countries table appropriately.

I'm actually thinking about getting rid of our database seeds, they're kind of annoying to keep up to date, and I think we should point new developers to our public development database export instead.

**Comment by lgarron** [comment]
We're using JSON for WCA data already. Custom formats tend to be an anti-pattern; can we avoid them for this?

**Comment by viroulep** [comment]
I pictured the website would just use this to create the actual country list displayed to people, from the markdown file in the Regulations repository.

The "SQL" output was just there to easily create the seed file already present in the website!
Writing a migration and detecting changes seems not that easy, I'm open to any suggestion on how to do it automatically.
I don't expect the states list to change soon, so we could just make a diff between both list and figure out what changes should be done.

> We're using JSON for WRC data already. Custom formats tend to be an anti-pattern; can we avoid them for this?
Which part are you referring to?
Would you want to only use json? (ie: WRC writes json, json used by website)
Or Markdown->json only? (ie: WRC writes md, json used by the website for everything)

**Comment by jfly** [comment]
> Writing a migration and detecting changes seems not that easy, I'm open to any suggestion on how to do it automatically.

I got rid of all the annoying foreign keys in our database... can you just drop the countries table and re-import?

**Comment by viroulep** [comment]
Don't we have to handle people whose country has been dropped?
(right now there are at least people from Aruba and French Polynesia)

Le 15 mai 2017 6:59 PM, "Jeremy Fleischman" <notifications@github.com> a
écrit :

**Comment by jfly** [comment]
Ah, good point! How about have the migration fail if there are any persons with nonexistent countries? That would force people to handle those by hand.

**Comment by viroulep** [comment]
I've updated the PR to only emit json, and I'll soon submit the corresponding PR to the website (I've done the "hard" part, ie the migration + seeds, I'm missing the view).

Since this states list will be the "authority" for what should be in the website db, I added the option to pass a friendly id for countries.
More specifically:
```
(FR:_Europe) France
(CI:_Africa) Côte d'Ivoire
```
Will create a json with the following attributes:
```json
{
"info": "",
 "name": "France",
 "continent_id": "_Europe",
 "class": "state",
 "iso2": "FR",
 "id": "France"
},
{
"info": "",
 "name": "C\u00f4te d'Ivoire",
 "continent_id": "_Africa",
"class": "state",
"iso2": "CI",
"id": "Cote d_Ivoire"
}
```
Here the id can be built from the name (by transliteration + replace), and matches what we already have in the db.

However when the name is "United States" and the existing db id is "USA", the id can't be derived from the name.
To overcome that I made optional a "friendly_id":
```
(US:_North America:USA) United States
```
which produces:
```json
{
"info": "",
"name": "United States",
"continent_id": "_North America",
"class": "state",
"iso2": "US",
"id": "USA"
}
```
(Only USA and Korea need this if I didn't miss anything)

**Comment by jfly** [comment]
I'd like to get rid of these "friendly ids", but I guess the simplest thing to do for now is to keep them around?

**Comment by viroulep** [comment]
I don't know our db schema and its usage well enough to give a correct answer.

We have a couple of tables using "countryId" (=friendly id), and I had never heard of a bunch of them.
I would assume we just need to rename the column to "country_iso2" and write the corresponding migrations, as well as modifying the code using them.
It may implies modifying old and untested php code that may be used for results posting.

**Comment by viroulep** [comment]
I think that's probably best yes, we could get rid of both the "id" and "name" column at once!
(Since db names are currently unused in the Rails codebase).

**Comment by viroulep** [comment]
@jfly I've updated the PR with the pretty print + comment you ask on the WCA website, I think we're pretty much done here :)

**Pull request merged**
