### PR TITLE
Add Slovenian support

### PR DESCRIPTION
**Pull request by Nanush7**
Added Slovenian to languages.json

Checklist (from @viroulep):

- [x] Bump the compiler version.
- [ ] Deploy to pypi.
- [ ] On the website server, we should run pip3 install --upgrade wrc ([this](https://github.com/thewca/worldcubeassociation.org/blob/master/chef/site-cookbooks/wca/recipes/regulations_documents.rb#L22) is done automatically when bootstrapping a new server by this).
- [x] Merge https://github.com/thewca/wca-regulations-translations/pull/128 before updating the regulations on the website.

### CODE REVIEW

**Review by viroulep — APPROVED** [review]
As far as I'm concerned it looks good to me!

If I'm not mistaken the next steps for Slovenian to be properly buildable would be to:
  - bump the compiler version
  - deploy to pypi
  - (in the wca-regulations repository I don't think anything else is needed since we install the newest compiler package whenever a job is started)
  - on the website server, we should run `pip3 install --upgrade wrc` (this is done automatically when bootstrapping a new server by [this](https://github.com/thewca/worldcubeassociation.org/blob/master/chef/site-cookbooks/wca/recipes/regulations_documents.rb#L22))
  - and of course merge thewca/wca-regulations-translations#128 before updating the regulations on the website.

@Nanush7 are you aware of any other language that would need to be added?

**Comment by Nanush7** [comment]
No, only Slovenian for now.

**Comment by gregorbg** [comment]
Holding off on this until the other two "cosmetic" PRs are merged so that we can deploy them together.

**Comment by gregorbg** [comment]
In my opinion, adding a new language warrants a bump to `1.4.0`.

**Comment by Nanush7** [comment]
Thank you Gregor, I will bump the version later. The Slovenian translation has been merged, so we should be ready to merge this.

**Comment by Nanush7** [comment]
@gregorbg Kindly pinging you so we can proceed with deployment and make the translation available on the website.

**Comment by Nanush7** [comment]
@gregorbg ? :p

**Review by gregorbg — APPROVED** [review]

**Pull request merged**
